spring:
  datasource:
    url: jdbc:mysql://db:3306/simpleapp
    username: user
    password: root
    dialect: org.hibernate.dialect.MySQL8Dialect
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect