spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simpleapp
    username: root
    password: passworD1+
    dialect: org.hibernate.dialect.MySQL8Dialect
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect